# Generated by Django 5.2.1 on 2025-05-29 20:19

import django.db.models.functions.text
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_url", models.URLField(max_length=2000)),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        default=api.models.create_short_code,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "shortened_url",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Value("http://localhost:8000/"), "short_code"
                        ),
                        output_field=models.URLField(),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
